APIs
ng-anhhtuann/iGHTK pull request #4
Opened 2022-08-01 09:16 UTC by ng-anhhtuann

2022-08-01 14:40 UTC, uranashel44 commented on src/main/java/com/example/GHTK/Repository/Repository.java
> +            Connection connection = DriverManager.getConnection(url, username, password);
Same

2022-08-01 14:40 UTC, uranashel44 commented on src/main/java/com/example/GHTK/Repository/Repository.java
> +            Connection connection = DriverManager.getConnection(url, username, password);
Same as above

2022-08-01 14:41 UTC, uranashel44 commented on src/main/java/com/example/GHTK/Repository/Repository.java
> +            Connection connection = DriverManager.getConnection(url, username, password);
Same

2022-08-01 14:41 UTC, uranashel44 commented on src/main/java/com/example/GHTK/Repository/Repository.java
>              Connection connection = DriverManager.getConnection(url, username, password);
Same

2022-08-01 14:41 UTC, uranashel44 requested changes
Some comments need to be updated, it is mandatory

2022-08-02 08:23 UTC, ng-anhhtuann commented on src/main/java/com/example/GHTK/Repository/Repository.java
> +    public Object queryArea() {
SQLException will be thrown on time per request to show users what's wrong with the input data they send.
SQLException is required in connection._getConnection()_

2022-08-06 16:34 UTC, uranashel44 approved these changes

2022-08-06 16:35 UTC, uranashel44 commented on src/main/java/com/example/GHTK/Ultilities/Database.java
> +public class Database {
It it singleton?

2022-08-08 18:10 UTC, uranashel44 approved these changes

2022-08-08 18:11 UTC, merged